type Query {
    profile(id: String!): Profile
    profiles(limit: Int): [Profile]
}

type Mutation {
    createProfile(name: String!): Profile
}

type Profile {
    id: ID!
    name: String!
    rules: [Rule]
}