type Query {
    rule(id: ID!): Rule
    rules(limit: Int): [Rule]
}

type Mutation {
    createRule(name: String!, description: String): Rule
}

type Rule {
    id: ID!
    name: String!
    description: String
}
